### PR TITLE
Fixes #10 : Fix incorrect DbSelect::count() when setted \PDO::ATTR_CASE => \PDO::CASE_LOWER in driver options

### LINKED ISSUE #10: some DbAdapter driver_options can make DbSelect::count() incorrect
### Bug Report

some DbAdapter driver_options can make DbSelect::count() incorrect

|    Q        |   A
|------------ | ------
| Version(s)  | 2.8.2

#### Summary

PDO::CASE_LOWER can make DbSelect::count() incorrect.
#### Current behavior

get NOTICE: Undefined index: C on xxxxx

#### How to reproduce

```php
$adapter = new Adapter([
            'driver'   => 'pdo_mysql',
            "driver_options" => [
                \PDO::ATTR_CASE => \PDO::CASE_LOWER,
            ],
         // other options ....
]);

$select = $sql->select();

$dbSelect = new DbSelect($select, xxxx)
$dbSelect->count();

// NOTICE: Undefined index: C on xxxxx
```

```php
// DbSelect::count()
public function count()
    {
        if ($this->rowCount !== null) {
            return $this->rowCount;
        }

        $select = $this->getSelectCount();

        $statement = $this->sql->prepareStatementForSqlObject($select);
        $result    = $statement->execute();
        $row       = $result->current();

        // !!! here return $row['c'] = 10，lower case key

        $this->rowCount = (int) $row[self::ROW_COUNT_COLUMN_NAME];

        return $this->rowCount;
    }
```

#### Expected behavior

check lower or upper case key，return the right count

### PR DESCRIPTION
**Pull request by samsonasik**
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

Fix incorrect DbSelect::count() when setted \PDO::ATTR_CASE => \PDO::CASE_LOWER in driver options

### CODE REVIEW

**Comment by samsonasik** [comment]
need to update mock driver in test

**Comment by samsonasik** [comment]
The easiest way probably create a separate class that uses small 'c' as column, or just change the `ROW_COUNT_COLUMN_NAME` constant value to small 'c'

**Review by froschdesign — CHANGES_REQUESTED** [review]
I think the solution is too complicated because the select query for counting contains only one column.

Some problems:

* PDO attribute is checked two times
* a new class constant is added to the class
* a concrete database adapter is added to the class

**Comment by froschdesign** [comment]
A possible unit test:

```php
public function testCountQueryWithLowerColumnNameShouldReturnValidResult()
{
    $this->dbSelect = new DbSelect($this->mockSelect, $this->mockSql);
    $this->mockResult
        ->expects($this->once())
        ->method('current')
        ->will($this->returnValue(['c' => 7]));

    $count = $this->dbSelect->count();
    $this->assertEquals(7, $count);
}
```

**Comment by samsonasik** [comment]
I simplified check with add "c" column in columns list, so if no isset "C" column, we can fallback to "c" column. @froschdesign I applied your test.

**Comment by samsonasik** [comment]
travis build green 🎉

File: src/Adapter/DbSelect.php [hunk 1]
```diff
@@ -122,7 +122,9 @@ public function count()
         $result    = $statement->execute();
         $row       = $result->current();
 
-        $this->rowCount = (int) $row[self::ROW_COUNT_COLUMN_NAME];
+        $this->rowCount = isset($row[self::ROW_COUNT_COLUMN_NAME])
+            ? (int) $row[self::ROW_COUNT_COLUMN_NAME]
+            : (int) $row['c'];
```
Comment (froschdesign) [inline src/Adapter/DbSelect.php]: Should the column name not be based on the constant?

File: src/Adapter/DbSelect.php [hunk 2]
```diff
@@ -145,7 +147,10 @@ protected function getSelectCount()
 
         $countSelect = new Select;
 
-        $countSelect->columns([self::ROW_COUNT_COLUMN_NAME => new Expression('COUNT(1)')]);
+        $countSelect->columns([
+            self::ROW_COUNT_COLUMN_NAME => new Expression('COUNT(1)'),
+            'c' => new Expression('COUNT(1)')
```
Comment (froschdesign) [inline src/Adapter/DbSelect.php]: The same here.

File: src/Adapter/DbSelect.php (hunk 1 above)
Comment (samsonasik) [reply src/Adapter/DbSelect.php]: updated.

File: src/Adapter/DbSelect.php (hunk 2 above)
Comment (samsonasik) [reply src/Adapter/DbSelect.php]: updated.

**Comment by samsonasik** [comment]
travis build green 🎉

File: src/Adapter/DbSelect.php [hunk 3]
```diff
@@ -122,7 +122,9 @@ public function count()
         $result    = $statement->execute();
         $row       = $result->current();
 
-        $this->rowCount = (int) $row[self::ROW_COUNT_COLUMN_NAME];
+        $this->rowCount = isset($row[self::ROW_COUNT_COLUMN_NAME])
+            ? (int) $row[self::ROW_COUNT_COLUMN_NAME]
+            : (int) $row[strtolower(self::ROW_COUNT_COLUMN_NAME)];
```
Comment (weierophinney) [inline src/Adapter/DbSelect.php]: What happens if this element is not present in the array?

File: src/Adapter/DbSelect.php [hunk 4]
```diff
@@ -145,7 +147,10 @@ protected function getSelectCount()
 
         $countSelect = new Select;
 
-        $countSelect->columns([self::ROW_COUNT_COLUMN_NAME => new Expression('COUNT(1)')]);
+        $countSelect->columns([
+            self::ROW_COUNT_COLUMN_NAME => new Expression('COUNT(1)'),
+            strtolower(self::ROW_COUNT_COLUMN_NAME) => new Expression('COUNT(1)')
```
Comment (weierophinney) [inline src/Adapter/DbSelect.php]: Will this work on all databases? Will some databases throw an error if one of the columns does not exist, and/or return a count of zero in that scenario?

**Review by weierophinney — CHANGES_REQUESTED** [review]
I'm worried about how portable this is: is it going to work across all drivers PDO supports? what about non-PDO drivers?

I'm wondering if we either need (a) a flag to enable this behavior, with documentation about when you'd enable that flag, and/or (b) a separate adapter that does this. Right now, since we mock the connections, we may be getting a false sense of security that this approach works, when it may only work in select cases.

File: src/Adapter/DbSelect.php (hunk 3 above)
Comment (samsonasik) [reply src/Adapter/DbSelect.php]: previously, it uses array in fields, so it added column to array

File: src/Adapter/DbSelect.php (hunk 4 above)
Comment (samsonasik) [reply src/Adapter/DbSelect.php]: currently tested and worked in mysql

Comment (samsonasik) [reply src/Adapter/DbSelect.php]: I tested in PostgreSQL and it works:

```
test=# select COUNT(1) as C, COUNT(1) as c from tbl_user;
 c | c 
---+---
 4 | 4
(1 row)
```

Comment (samsonasik) [reply src/Adapter/DbSelect.php]: I tried with both uppercase in PostgreSQL as well, and it works:

```sql
test=# select COUNT(1) as C, COUNT(1) as C from tbl_user;
 c | c 
---+---
 4 | 4
(1 row)
```

Comment (samsonasik) [reply src/Adapter/DbSelect.php]: Just tried in SQLite3 as well, and work with both uppercase and lowercase : 

```sql
➜  ~ sqlite3
SQLite version 3.32.3 2020-06-18 14:00:33
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> create table tbl_user(email primary key not null, name varchar(255));
sqlite> insert into tbl_user values('samsonasik@gmail.com', 'Abdul Malik Ikhsan');
sqlite> select COUNT(1) as C, COUNT(1) as C from tbl_user;
1|1
sqlite> select COUNT(1) as C, COUNT(1) as c from tbl_user;
1|1

```

Comment (froschdesign) [reply src/Adapter/DbSelect.php]: Does the database query really need to be extended? Can we really ensure for all DBMS that it works or that there are no performance problems? I think it introduced more questions / problems.

Why not check the result for the default column name in upper case and as an alternative in lower case?

Comment (samsonasik) [reply src/Adapter/DbSelect.php]: @froschdesign  updated. should be ok now.

**Comment by samsonasik** [comment]
@froschdesign @weierophinney merge-able now ? Thank you.

**Review by froschdesign — APPROVED** [review]

File: src/Adapter/DbSelect.php (hunk 3 above)
Comment (weierophinney) [inline src/Adapter/DbSelect.php]: What happens when the lowercase version is not present? This is likely to raise a warning.

I'd argue this should be done as follows:

```php
$this->rowCount = $this->locateRowCount($row);
```

with the following helper method:

```php
/* Not sure if `array` is correct here, or if this could be an `ArrayAccess` instance */
private function locateRowCount(array $row): int
{
    if (array_key_exists(self::ROW_COUNT_COLUMN_NAME, $row)) {
        return (int) $row[self::ROW_COUNT_COLUMN_NAME];
    }

    $lowerCaseColumnName = strtolower(self::ROW_COUNT_COLUMN_NAME);
    if (array_key_exists($lowerCaseColumnName, $row)) {
        return (int) $row[$lowerCaseColumnName];
    }

    throw new LogicException('Unable to determine row count; missing row count column in result');
}
```

This will satisfy #10, while also making the code less brittle.

**Review by weierophinney — CHANGES_REQUESTED** [review]

File: src/Adapter/DbSelect.php (hunk 3 above)
Comment (samsonasik) [reply src/Adapter/DbSelect.php]: @weierophinney implemented
